# Generated by Django 3.1.1 on 2020-10-01 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(max_length=30)),
                ('num_doc', models.CharField(max_length=15)),
                ('ape_pat', models.CharField(max_length=30)),
                ('ape_mat', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=40)),
                ('fecha_nac', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('estado', models.CharField(default=1, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_user', models.CharField(max_length=40)),
                ('pass_user', models.CharField(max_length=256)),
                ('estado', models.CharField(default=1, max_length=5)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DP.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='dp_diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultrafil', models.IntegerField()),
                ('pres_art', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user_reg', models.CharField(max_length=40)),
                ('fecha_nac', models.DateField(auto_now_add=True)),
                ('user_mod', models.CharField(max_length=40)),
                ('fecha_mod', models.DateField(auto_now_add=True)),
                ('user_eli', models.CharField(max_length=40)),
                ('fecha_eli', models.DateField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DP.paciente')),
            ],
        ),
    ]
