# Generated by Django 3.1.1 on 2020-10-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dp_diario',
            old_name='fecha_nac',
            new_name='fecha_reg',
        ),
        migrations.AlterField(
            model_name='dp_diario',
            name='user_eli',
            field=models.CharField(default='USER', max_length=40),
        ),
        migrations.AlterField(
            model_name='dp_diario',
            name='user_mod',
            field=models.CharField(default='USER', max_length=40),
        ),
        migrations.AlterField(
            model_name='dp_diario',
            name='user_reg',
            field=models.CharField(default='USER', max_length=40),
        ),
    ]
