# Generated by Django 3.1.1 on 2020-10-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DP', '0002_auto_20200930_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dp_diario',
            name='fecha_eli',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dp_diario',
            name='fecha_mod',
            field=models.DateField(auto_now=True),
        ),
    ]
