# Generated by Django 3.1.1 on 2022-02-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DP', '0003_auto_20200930_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='examenLaboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(max_length=4)),
                ('periodo', models.CharField(max_length=6)),
                ('area', models.CharField(max_length=40)),
                ('servicio', models.CharField(max_length=20)),
                ('actividad', models.CharField(max_length=40)),
                ('subactividad', models.CharField(max_length=40)),
                ('acto_medico', models.CharField(max_length=10)),
                ('fecha_atencion', models.DateField()),
                ('fecha_solicitud', models.DateField()),
                ('fecha_cita', models.DateField()),
                ('fecha_resultado', models.DateField()),
                ('num_solicitud', models.CharField(max_length=10)),
                ('dni_solicita', models.CharField(max_length=10)),
                ('prof_solicita', models.CharField(max_length=100)),
                ('tipexamen', models.CharField(max_length=10)),
                ('arealab', models.CharField(max_length=20)),
                ('sede', models.CharField(max_length=20)),
                ('examen', models.CharField(max_length=10)),
                ('descexamen', models.CharField(max_length=40)),
                ('dni_profesional', models.CharField(max_length=10)),
                ('profesional', models.CharField(max_length=100)),
                ('dni_paciente', models.CharField(max_length=15)),
                ('h_c', models.CharField(max_length=10)),
                ('paciente', models.CharField(max_length=100)),
                ('telefonos', models.CharField(max_length=15)),
                ('annos', models.CharField(max_length=3)),
                ('meses', models.CharField(max_length=2)),
                ('dias', models.CharField(max_length=2)),
                ('sexo', models.CharField(max_length=6)),
                ('tipo_paciente', models.CharField(max_length=20)),
                ('cas_adscripcion', models.CharField(max_length=6)),
                ('diagnostico', models.CharField(max_length=10)),
                ('des_diagn', models.CharField(max_length=100)),
                ('tip_diagn', models.CharField(max_length=10)),
                ('resultado', models.CharField(max_length=20)),
                ('categoria_resul', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('usuario_registro', models.CharField(max_length=20)),
                ('informe_resultado', models.CharField(max_length=200)),
                ('orden_plantilla', models.CharField(max_length=6)),
                ('desc_plantilla', models.CharField(max_length=40)),
                ('valor_resultado', models.CharField(max_length=20)),
                ('unidadvalor', models.CharField(max_length=40)),
                ('observresultado', models.CharField(max_length=40)),
                ('usario_modifica', models.CharField(max_length=20)),
                ('fecha_modifica', models.DateField()),
                ('centro_origen_solicitud', models.CharField(max_length=4)),
                ('codresul_covid', models.CharField(max_length=6)),
                ('resultado_covid', models.CharField(max_length=40)),
                ('hora_registro', models.CharField(max_length=6)),
                ('autogenerado', models.CharField(max_length=20)),
                ('desc_topico', models.CharField(max_length=40)),
            ],
        ),
    ]
