# Generated by Django 3.1.1 on 2022-02-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DP', '0004_examenlaboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='descexamen',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='hora_registro',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='telefonos',
            field=models.CharField(max_length=50),
        ),
    ]
