# Generated by Django 3.1.1 on 2022-02-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DP', '0006_auto_20220216_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='acto_medico',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='annos',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='area',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='arealab',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='autogenerado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='cas_adscripcion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='centro',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='centro_origen_solicitud',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='codresul_covid',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='des_diagn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='desc_plantilla',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='desc_topico',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='descexamen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='dias',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='dni_paciente',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='dni_profesional',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='dni_solicita',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='examen',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='fecha_modifica',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='fecha_resultado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='h_c',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='hora_registro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='meses',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='num_solicitud',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='orden_plantilla',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='paciente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='periodo',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='prof_solicita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='profesional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='resultado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='resultado_covid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='sede',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='servicio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='sexo',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='telefonos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='tip_diagn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='tipexamen',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='tipo_paciente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='usario_modifica',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='usuario_registro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='valor_resultado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
