# Generated by Django 3.1.1 on 2022-02-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DP', '0007_auto_20220216_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='fecha_atencion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='fecha_cita',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='fecha_modifica',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='fecha_registro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='fecha_resultado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='fecha_solicitud',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
