# Generated by Django 3.1.1 on 2022-02-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DP', '0008_auto_20220216_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tipoTrata',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
