# Generated by Django 3.1.1 on 2022-02-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DP', '0009_paciente_tipotrata'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='primSesion',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
